### PR TITLE
Add pdb files back

### PR DESCRIPTION
**Pull request by normj**
*Issue #, if available:*
https://github.com/aws/aws-logging-dotnet/pull/81#issuecomment-485118975

*Description of changes:*
Adding back PDB files to NuGet packages. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by snakefoot** [comment]
Consider also adding this:

```xml
<PropertyGroup> <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb;.xml</AllowedOutputExtensionsInPackageBuildOutputFolder>
</PropertyGroup>
```

And maybe also add package-reference to: https://www.nuget.org/packages/Microsoft.SourceLink.GitHub/ (Should automatically become a hidden dependency).

**Comment by normj** [comment]
I do want to get source link setup but the change requires more then just adding that library right now.

What benefit would `AllowedOutputExtensionsInPackageBuildOutputFolder` add? When I run the build now I'm getting the pdb, xml and dll in the package file.

**Comment by sattpat** [comment]
We already add <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder> into our projects.  Do we need to add .xml extensions ?

**Comment by snakefoot** [comment]
`.xml` includes the xml-documentation for your properties. So when using your API, then you will get syntax-help that will display `/// <summary>`-documentation.

**Pull request merged**
