### PR TITLE
Replaced nuspec files with dotnet pack

### PR DESCRIPTION
**Pull request by snakefoot**
*Description of changes:*

- Includes XML documentation
- Added NetStandard 2.0 as target
- Activated TreatWarningsAsErrors (And fixed the warnings)
- Changed URLs in nuget-package to use https

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by normj** [comment]
Thanks for the PR, I didn't realize at first how much cleanup you done. I have merged it into the dev branch.

**Comment by snakefoot** [comment]
Closing PR as it has been merged into DEV-branch

**Comment by snakefoot** [comment]
@normj Now created new PR for you #71

**Comment by normj** [comment]
@snakefoot Great, taking a look.

**Pull request closed without merging**
