### PR TITLE
Removing PDB files and unused system diagnostics package

### PR DESCRIPTION
**Pull request by sattpat**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by snakefoot** [comment]
@normj Why remove the PDB-files? They are very useful when troubleshooting, and the new portable format are very small in size.

https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages

But if it means you are going to publish a `.snupkg` then fine with me:

https://blog.nuget.org/20181116/Improved-debugging-experience-with-the-NuGet-org-symbol-server-and-snupkg.html

**Comment by sattpat** [comment]
Thanks for reporting this. I will have a discussion with the team and get back to you asap.

**Comment by normj** [comment]
We are going to add the PDB back. It was done to reduce the size of the packages but I believe we shouldn't remove the PDB until we are ready to push the `.snupkg` packages.

**Comment by snakefoot** [comment]
When using dotnet pack then one needs to do extra magic to have xml-doc and pdb-symbols in the output nuget-package


Sent from my Sony Xperia


---- Norm Johanson wrote ----


We are going to add the PDB back. It was done to reduce the size of the packages but I believe we shouldn't remove the PDB until we are ready to push the .snupkg packages.

**Pull request merged**
