### PR TITLE
 NLog AWSTarget apply Layout logic to config-properties 

### LINKED ISSUE #47: Evaluate NLog parameters in AwsTarget Class
Hi,

I found out that NLog parameters are NOT evaluated when they are passed to the AWSTarget. 
Any variable, or renderers used within these parameters will not get evaluated.

For instance:
```
        [RequiredParameter]
        public string LogGroup
        {
            get { return _config.LogGroup; }
            set { _config.LogGroup = value; }
        }
```

Does not evaluate code like: `${when:when='${environment:ASPNETCORE_ENVIRONMENT}'=='Production':inner=prd:else=uat}`

To make it work, I had to change the AwsTarget class and call SimpleLayout.Evaluate when assigning value to AWSLoggerConfig.

```
        [RequiredParameter]
        public string LogGroup
        {
            get => _config.LogGroup;
            set => _config.LogGroup = SimpleLayout.Evaluate(value);
        }
```

I'm not sure it's a good practice, but it solved my "issue"

### PR DESCRIPTION
**Pull request by snakefoot**
Support for LogGroup + Region + Profile + ProfilesLocation + LogStreamNameSuffix

Resolves #47

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by normj** [comment]
Can you explain what is the purpose of using the RenderSimpleLayout method?

**Comment by snakefoot** [comment]
Allows one to inject values directly from appsettings.json<http://appsettings.json> or app.config<http://app.config> or NLog GDC


Sent from my Sony Xperia


---- Norm Johanson wrote ----


Can you explain what is the purpose of using the RenderSimpleLayout method?

**Comment by normj** [comment]
Merged into dev. I'll respond back when the change has shipped.

**Comment by seroche** [comment]
Great news! let me know when it is released

**Comment by snakefoot** [comment]
@normj Polite poke. Any chance for a release coming?

**Comment by normj** [comment]
@snakefoot Thanks for the polite poke. This week is a bit crazy right now for the upcoming AWS Summit. When that is over I'll see about getting a release out.

**Comment by snakefoot** [comment]
@normj Looks like there are AWS summits all around the globe and all year around :) Well looking forward to the upcoming release :)

**Comment by normj** [comment]
@snakefoot Fair enough, I meant last week's AWS Summit at Santa Clara California. I was speaking at it which caused my schedule to become very hectic. I'll push to get a release out soon.

**Comment by normj** [comment]
Update, this didn't get forgotten this week. We are in the middle of redoing our build/release infrastructure for all of our repositories which is causing a bit of delay.

**Comment by snakefoot** [comment]
@normj Looking forward to a release where NetCore is again back on track. Would be great if you as a library provider could also reach that goal. Opening the door for building NetCore-applications.

**Comment by snakefoot** [comment]
@normj Polite bump for a release to happen

**Comment by snakefoot** [comment]
@normj Time to get new glasses. See a nuget-package has been released a week ago:

https://www.nuget.org/packages/AWS.Logger.NLog/

And it also includes NetStandard2 support. Thank you :)

**Comment by normj** [comment]
Yeah, sorry you should have been notified when it was released. I was at MS Build and somebody else did the release and I didn't let them know to update the PR. Thanks again for all of your help to improve these libraries. We finished our new build system so we should be able to do releases of this library much quicker now.

**Comment by snakefoot** [comment]
@normj Guess the other libraries should also be released. So they can get some NetCore-loving (Increase all to version 1.3.2 first).

**Comment by snakefoot** [comment]
@normj Any plans for releasing all components as ver. 1.3.3 ?

**Pull request merged**
