### PR TITLE
Implementing Retention Policy to Cloudwatch

### PR DESCRIPTION
**Pull request by DebashishSaha**
*Issue #, if available:*

*Description of changes:*
1. Adding Retention Policy into Cloudwatch
3. Added Test cases
4. Sample test with retention Policy

image

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by DebashishSaha** [comment]
hi @normj could you please review this PR

**Review by li5tun — APPROVED** [review]

**Comment by normj** [comment]
Hi @DebashishSaha sorry this PR didn't get the attention it deserves.

Sorry but I have to reject because it relies on configuring the retention period in the `LogEventTransmissionSetup` where the log group and stream are setup. That method is only called if the put events method fails for a resource not found. To make sure the library has fast startup time we avoid the control plane setup calls unless we find something missing. With this PR's new retention property in order to make that work we have to always call the `PutRetentionPolicy` operation at startup and slow down startup. That could get extra problematic if a large number instances of the same process startup at the same time.

**Comment by DebashishSaha** [comment]
makes sense if we want to reduce startup time. thanks @normj

**Comment by Will-Boulton** [comment]
@normj I was thinking of having another crack at this with some changes to move `PutRetentionPolicy` off the startup thread to prevent blocking there. 

Sound alright by you?

**Comment by DebashishSaha** [comment]
Apologies for coming late into this . thanks a lot @Will-Boulton  for this effort and making the AWS team understand that its a feature in need. Your PR will be helpful :) thanks

**Pull request closed without merging**
